package com.commercepal.apiservice.orders.tracking.repository;

import com.commercepal.apiservice.orders.core.model.Order;
import com.commercepal.apiservice.orders.core.model.OrderItem;
import com.commercepal.apiservice.orders.tracking.enums.TrackingEventType;
import com.commercepal.apiservice.orders.tracking.model.OrderTrackingEvent;
import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * OrderTrackingEventRepository
 * <p>
 * Repository for tracking event operations with optimized queries.
 */
@Repository
public interface OrderTrackingEventRepository extends JpaRepository<OrderTrackingEvent, Long> {

  /**
   * Find all tracking events for an order, ordered by timestamp descending Most recent events
   * first
   */
  List<OrderTrackingEvent> findByOrderOrderByEventTimestampDesc(Order order);

  /**
   * Find all tracking events for an order, ordered by timestamp ascending Chronological order
   * (oldest first)
   */
  List<OrderTrackingEvent> findByOrderOrderByEventTimestampAsc(Order order);

  /**
   * Find all customer-visible tracking events for an order Most recent events first
   */
  List<OrderTrackingEvent> findByOrderAndIsCustomerVisibleTrueOrderByEventTimestampDesc(
      Order order);

  /**
   * Find all tracking events for a specific order item
   */
  List<OrderTrackingEvent> findByOrderItemOrderByEventTimestampDesc(OrderItem orderItem);

  /**
   * Find the most recent tracking event for an order
   */
  @Query("SELECT e FROM OrderTrackingEvent e WHERE e.order = :order " +
      "ORDER BY e.eventTimestamp DESC LIMIT 1")
  Optional<OrderTrackingEvent> findLatestByOrder(@Param("order") Order order);

  /**
   * Find the currently active event for an order
   */
  Optional<OrderTrackingEvent> findByOrderAndIsActiveEventTrue(Order order);

  /**
   * Find all active events for an order (There should typically only be one, but this handles edge
   * cases)
   */
  List<OrderTrackingEvent> findAllByOrderAndIsActiveEventTrue(Order order);

  /**
   * Check if a specific event type exists for an order
   */
  boolean existsByOrderAndEventType(Order order, TrackingEventType eventType);

  /**
   * Find events by tracking number Useful for cross-referencing with carrier tracking systems
   */
  List<OrderTrackingEvent> findByTrackingNumberOrderByEventTimestampDesc(String trackingNumber);

  /**
   * Find events by event type for an order
   */
  List<OrderTrackingEvent> findByOrderAndEventTypeOrderByEventTimestampDesc(
      Order order, TrackingEventType eventType);

  /**
   * Count total events for an order
   */
  long countByOrder(Order order);

  /**
   * Count customer-visible events for an order
   */
  long countByOrderAndIsCustomerVisibleTrue(Order order);

  /**
   * Find all auto-generated events for an order
   */
  List<OrderTrackingEvent> findByOrderAndIsAutoGeneratedTrueOrderByEventTimestampDesc(Order order);

  /**
   * Find all manually created events for an order
   */
  List<OrderTrackingEvent> findByOrderAndIsAutoGeneratedFalseOrderByEventTimestampDesc(
      Order order);

  /**
   * Delete all tracking events for an order Use with caution - typically only for testing or order
   * cleanup
   */
  void deleteByOrder(Order order);

  /**
   * Find events by location (for geographic tracking analysis)
   */
  List<OrderTrackingEvent> findByLocationContainingIgnoreCaseOrderByEventTimestampDesc(
      String location);
}
