package com.commercepal.apiservice.payments.oderPayment;

import com.commercepal.apiservice.orders.core.model.Order;
import com.commercepal.apiservice.orders.enums.PaymentStatus;
import com.commercepal.apiservice.shared.enums.SupportedCurrency;
import com.commercepal.apiservice.users.customer.Customer;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@EntityListeners(AuditingEntityListener.class)
@Table(
    name = "order_payments",
    indexes = {
        @Index(name = "idx_payment_order", columnList = "order_id"),
        @Index(name = "idx_payment_customer", columnList = "customer_id"),
        @Index(name = "idx_payment_status", columnList = "status"),
        @Index(name = "idx_payment_gateway_ref", columnList = "gateway_reference"),
        @Index(name = "idx_payment_created_at", columnList = "created_at")
    },
    uniqueConstraints = {
        @UniqueConstraint(
            name = "uk_payment_reference",
            columnNames = "payment_reference"
        )
    }
)
public class OrderPayment {

  /**
   * Version field for optimistic locking. Automatically incremented on each update.
   */
  @Version
  @Column(name = "version", nullable = false)
  @Builder.Default
  private final Long version = 0L;
  @Id
  @Column(name = "id")
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;
  /**
   * When this payment record was created.
   */
  @CreatedDate
  @Column(name = "created_at", nullable = false, updatable = false)
  private LocalDateTime createdAt;

  /**
   * Order this payment belongs to.
   */
  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(
      name = "order_id",
      nullable = false,
      foreignKey = @ForeignKey(name = "fk_payment_order")
  )
  private Order order;

  /**
   * Customer who owns this payment. Explicit for reporting, reconciliation, and disputes.
   */
  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(
      name = "customer_id",
      nullable = false,
      foreignKey = @ForeignKey(name = "fk_payment_customer")
  )
  private Customer customer;

  /**
   * Internal, idempotency-safe payment reference. Generated by the system before calling the
   * gateway.
   */
  @Column(name = "payment_reference", nullable = false, unique = true, length = 100)
  private String reference;

  /**
   * External gateway transaction reference. Nullable until gateway responds.
   */
  @Column(name = "gateway_reference", length = 255)
  private String gatewayReference;

  @Column(name = "gateway")
  private String gateway;

  @Column(name = "account_number")
  private String accountNumber;

  // =========================
  // PAYMENT DETAILS
  // =========================

  @Column(name = "amount", precision = 15, scale = 2, nullable = false)
  private BigDecimal amount;

  @Enumerated(EnumType.STRING)
  @Column(name = "currency", nullable = false, length = 3)
  private SupportedCurrency currency;

  @Enumerated(EnumType.STRING)
  @Column(name = "status", nullable = false, length = 20)
  @Builder.Default
  private PaymentStatus status = PaymentStatus.PENDING;

  // =========================
  // PROVIDER INTERACTION – INITIAL REQUEST
  // =========================

  /**
   * Payload sent to payment provider during initial payment initiation.
   */
  @Column(name = "init_request_payload", columnDefinition = "TEXT")
  private String initRequestPayload;

  /**
   * Immediate synchronous response from provider (if any).
   */
  @Column(name = "init_response_payload", columnDefinition = "TEXT")
  private String initResponsePayload;

  /**
   * When the initial request was sent.
   */
  @Column(name = "init_requested_at", nullable = false)
  private LocalDateTime initRequestedAt;

  /**
   * When the provider responded synchronously.
   */
  @Column(name = "init_responded_at")
  private LocalDateTime initRespondedAt;

  // =========================
// PROVIDER INTERACTION – WEBHOOK
// =========================

  /**
   * Raw webhook payload received from provider.
   */
  @Column(name = "webhook_payload", columnDefinition = "TEXT")
  private String webhookPayload;

  /**
   * When webhook was received.
   */
  @Column(name = "webhook_received_at")
  private LocalDateTime webhookReceivedAt;

  /**
   * Provider status reported via webhook.
   */
  @Column(name = "webhook_status", length = 50)
  private String webhookStatus;

// =========================
// PROVIDER INTERACTION – VERIFICATION / QUERY
// =========================

  /**
   * Payload used to query or confirm payment status (e.g. transaction status API).
   */
  @Column(name = "verify_request_payload", columnDefinition = "TEXT")
  private String verifyRequestPayload;

  /**
   * Response from verification request.
   */
  @Column(name = "verify_response_payload", columnDefinition = "TEXT")
  private String verifyResponsePayload;

  /**
   * When verification request was made.
   */
  @Column(name = "verify_requested_at")
  private LocalDateTime verifyRequestedAt;

  /**
   * When verification response was received.
   */
  @Column(name = "verify_responded_at")
  private LocalDateTime verifyRespondedAt;

  // =========================
// FINAL RESOLUTION
// =========================

  /**
   * Final provider message explaining outcome. Example: "Approved", "Insufficient funds"
   */
  @Column(name = "provider_final_message", length = 500)
  private String providerFinalMessage;

  /**
   * When payment reached a terminal state (SUCCESS / FAILED / CANCELLED).
   */
  @Column(name = "resolved_at")
  private LocalDateTime resolvedAt;

  public void recordInitRequest(String payload) {
    this.initRequestPayload = payload;
    this.initRequestedAt = LocalDateTime.now();
  }

  public void recordInitResponse(String payload) {
    this.initResponsePayload = payload;
    this.initRespondedAt = LocalDateTime.now();
  }

  public void recordWebhook(String payload, String status) {
    this.webhookPayload = payload;
    this.webhookStatus = status;
    this.webhookReceivedAt = LocalDateTime.now();
  }

  public void recordVerification(String request, String response) {
    this.verifyRequestPayload = request;
    this.verifyResponsePayload = response;
    this.verifyRespondedAt = LocalDateTime.now();
  }

  public void resolve(PaymentStatus status, String message) {
    this.status = status;
    this.providerFinalMessage = message;
    this.resolvedAt = LocalDateTime.now();
  }

}
