package com.commercepal.apiservice.orders.tracking.service;

import com.commercepal.apiservice.orders.core.model.Order;
import com.commercepal.apiservice.orders.core.model.OrderItem;
import com.commercepal.apiservice.orders.tracking.enums.TrackingEventType;
import com.commercepal.apiservice.orders.tracking.model.OrderTrackingEvent;
import com.commercepal.apiservice.orders.tracking.repository.OrderTrackingEventRepository;
import java.time.LocalDateTime;
import java.util.List;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * OrderTrackingService
 * <p>
 * Service for managing order tracking events and timeline. Handles automatic event creation,
 * timeline retrieval, and event management.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class OrderTrackingService {

  private final OrderTrackingEventRepository trackingEventRepository;

  /**
   * Create a new tracking event for an order
   *
   * @param order       Order to track
   * @param eventType   Type of event
   * @param location    Geographic location (optional)
   * @param description Event description (optional, uses default from eventType if null)
   * @return Created tracking event
   */
  @Transactional
  public OrderTrackingEvent createTrackingEvent(
      Order order,
      TrackingEventType eventType,
      String location,
      String description) {
    return createTrackingEvent(order, null, eventType, location, description, null, null, null,
        true, true);
  }

  /**
   * Create a new tracking event for an order with full control
   *
   * @param order             Order to track
   * @param orderItem         Specific order item (null for order-level events)
   * @param eventType         Type of event
   * @param location          Geographic location
   * @param description       Event description
   * @param carrierName       Carrier name
   * @param trackingNumber    Tracking number
   * @param metadata          Additional metadata in JSON format
   * @param isCustomerVisible Whether customers should see this event
   * @param isAutoGenerated   Whether this was auto-generated
   * @return Created tracking event
   */
  @Transactional
  public OrderTrackingEvent createTrackingEvent(
      Order order,
      OrderItem orderItem,
      TrackingEventType eventType,
      String location,
      String description,
      String carrierName,
      String trackingNumber,
      String metadata,
      boolean isCustomerVisible,
      boolean isAutoGenerated) {

    // Use event type's default description if none provided
    String finalDescription = description != null ? description : eventType.getDescription();

    // Create the tracking event
    OrderTrackingEvent trackingEvent = OrderTrackingEvent.builder()
        .order(order)
        .orderItem(orderItem)
        .eventType(eventType)
        .eventTimestamp(LocalDateTime.now())
        .location(location)
        .description(finalDescription)
        .carrierName(carrierName)
        .trackingNumber(trackingNumber)
        .metadata(metadata)
        .isCustomerVisible(isCustomerVisible && eventType.isCustomerVisible())
        .isActiveEvent(false) // Will be set as active separately if needed
        .isAutoGenerated(isAutoGenerated)
        .build();

    OrderTrackingEvent saved = trackingEventRepository.save(trackingEvent);

    log.info("Created tracking event: orderId={}, orderNumber={}, eventType={}, location={}",
        order.getId(), order.getOrderNumber(), eventType, location);

    // Mark this event as active if it's a significant tracking event
    if (shouldBeActiveEvent(eventType)) {
      markEventAsActive(saved);
    }

    return saved;
  }

  /**
   * Create a tracking event for a specific order item
   *
   * @param orderItem   Order item to track
   * @param eventType   Type of event
   * @param location    Geographic location
   * @param description Event description
   * @return Created tracking event
   */
  @Transactional
  public OrderTrackingEvent createItemTrackingEvent(
      OrderItem orderItem,
      TrackingEventType eventType,
      String location,
      String description) {
    return createTrackingEvent(
        orderItem.getOrder(),
        orderItem,
        eventType,
        location,
        description,
        null,
        orderItem.getProviderTrackingNumber(),
        null,
        true,
        true);
  }

  /**
   * Get complete tracking timeline for an order Returns events in reverse chronological order
   * (newest first)
   *
   * @param order Order to get timeline for
   * @return List of tracking events
   */
  @Transactional(readOnly = true)
  public List<OrderTrackingEvent> getOrderTimeline(Order order) {
    return trackingEventRepository.findByOrderOrderByEventTimestampDesc(order);
  }

  /**
   * Get customer-visible tracking timeline for an order Returns only events marked as
   * customer-visible
   *
   * @param order Order to get timeline for
   * @return List of customer-visible tracking events
   */
  @Transactional(readOnly = true)
  public List<OrderTrackingEvent> getCustomerTimeline(Order order) {
    return trackingEventRepository.findByOrderAndIsCustomerVisibleTrueOrderByEventTimestampDesc(
        order);
  }

  /**
   * Get tracking timeline in chronological order (oldest first) Useful for timeline visualization
   *
   * @param order Order to get timeline for
   * @return List of tracking events in chronological order
   */
  @Transactional(readOnly = true)
  public List<OrderTrackingEvent> getChronologicalTimeline(Order order) {
    return trackingEventRepository.findByOrderOrderByEventTimestampAsc(order);
  }

  /**
   * Mark a specific event as the active event Deactivates all other events for the same order
   *
   * @param event Event to mark as active
   */
  @Transactional
  public void markEventAsActive(OrderTrackingEvent event) {
    // Deactivate all currently active events for this order
    List<OrderTrackingEvent> currentActiveEvents = trackingEventRepository
        .findAllByOrderAndIsActiveEventTrue(event.getOrder());

    for (OrderTrackingEvent activeEvent : currentActiveEvents) {
      activeEvent.markAsInactive();
      trackingEventRepository.save(activeEvent);
    }

    // Mark the new event as active
    event.markAsActive();
    trackingEventRepository.save(event);

    log.debug("Marked event as active: orderId={}, eventType={}",
        event.getOrder().getId(), event.getEventType());
  }

  /**
   * Check if an event type should be marked as active/highlighted Active events are typically the
   * current stage in the delivery process
   */
  private boolean shouldBeActiveEvent(TrackingEventType eventType) {
    return switch (eventType) {
      // Major milestone events that should be highlighted
      case ORDER_CREATED, PAYMENT_CONFIRMED, ORDERED_ON_PROVIDER,
           SHIPPED_FROM_PROVIDER, CUSTOMS_CLEARANCE_STARTED,
           CUSTOMS_CLEARED, AT_LOCAL_HUB, OUT_FOR_DELIVERY,
           DELIVERED, CANCELLED, FAILED -> true;

      // Intermediate events that shouldn't be highlighted
      default -> false;
    };
  }

  /**
   * Add a manual note/event to the timeline Used by admins/agents to add custom tracking updates
   *
   * @param order       Order to add note to
   * @param description Note description
   * @param userId      User adding the note
   * @return Created tracking event
   */
  @Transactional
  public OrderTrackingEvent addManualNote(Order order, String description, Long userId) {
    OrderTrackingEvent event = OrderTrackingEvent.builder()
        .order(order)
        .eventType(TrackingEventType.NOTE_ADDED)
        .eventTimestamp(LocalDateTime.now())
        .description(description)
        .isCustomerVisible(false)
        .isAutoGenerated(false)
        .createdByUserId(userId)
        .build();

    return trackingEventRepository.save(event);
  }

  /**
   * Check if a specific event type has occurred for an order
   *
   * @param order     Order to check
   * @param eventType Event type to look for
   * @return true if event exists
   */
  @Transactional(readOnly = true)
  public boolean hasEvent(Order order, TrackingEventType eventType) {
    return trackingEventRepository.existsByOrderAndEventType(order, eventType);
  }

  /**
   * Get the most recent tracking event for an order
   *
   * @param order Order to get latest event for
   * @return Latest tracking event, or null if none exist
   */
  @Transactional(readOnly = true)
  public OrderTrackingEvent getLatestEvent(Order order) {
    return trackingEventRepository.findLatestByOrder(order).orElse(null);
  }

  /**
   * Update tracking from external provider This would integrate with provider APIs (AliExpress,
   * Amazon, etc.) For now, it's a placeholder for future implementation
   *
   * @param order Order to refresh tracking for
   */
  @Transactional
  public void refreshProviderTracking(Order order) {
    // TODO: Integrate with external provider APIs to fetch latest tracking
    // For now, just create a tracking update event
    createTrackingEvent(
        order,
        TrackingEventType.TRACKING_UPDATED,
        null,
        "Tracking information refreshed from provider");

    log.info("Refreshed provider tracking for order: {}", order.getOrderNumber());
  }

  /**
   * Delete all tracking events for an order Use with extreme caution - typically only for testing
   *
   * @param order Order to delete events for
   */
  @Transactional
  public void deleteAllEvents(Order order) {
    trackingEventRepository.deleteByOrder(order);
    log.warn("Deleted all tracking events for order: {}", order.getOrderNumber());
  }
}
